-- 01_schema.sql : tables, constraints, indexes. Safe to re-run.
-- Run order: 01 -> 02 -> 03 -> 04 -> 05 (then 06 once, after creating your admin user)

create extension if not exists pgcrypto;

-- ---------- event_settings (single row) ----------
create table if not exists public.event_settings (
  id                   int primary key default 1 check (id = 1),
  name                 text not null default 'My Event',
  date_text            text not null default '',
  venue                text not null default '',
  description          text not null default '',
  contact_phone        text not null default '',
  contact_email        text not null default '',
  payment_instructions text not null default '',
  terms_text           text not null default '',
  sales_open           boolean not null default false,
  sales_start          timestamptz,
  sales_end            timestamptz,
  closed_message       text not null default 'Ticket sales are closed.',
  max_per_order        int not null default 5 check (max_per_order between 1 and 50),
  logo_path            text,
  banner_path          text,
  theme                jsonb not null default '{}'::jsonb,
  ticket_design        jsonb not null default '{}'::jsonb,
  email_templates      jsonb not null default '{}'::jsonb,
  updated_at           timestamptz not null default now()
);

-- ---------- ticket_types ----------
create table if not exists public.ticket_types (
  id              bigint generated by default as identity primary key,
  name            text not null,
  description     text not null default '',
  price           int  not null default 0 check (price >= 0),
  capacity        int  not null default 0 check (capacity >= 0),
  payment_qr_path text,
  accent_color    text,
  active          boolean not null default true,
  sort_order      int not null default 0,
  created_at      timestamptz not null default now()
);

-- ---------- orders ----------
create sequence if not exists public.order_no_seq start 1001;

create table if not exists public.orders (
  id              bigint generated by default as identity primary key,
  order_no        text not null unique,
  token           text not null unique,
  type_id         bigint not null references public.ticket_types(id) on delete restrict,
  type_name       text not null,
  unit_price      int  not null,
  qty             int  not null check (qty > 0),
  amount          int  not null check (amount >= 0),
  buyer_name      text not null,
  email           text not null,
  phone           text not null default '',
  payer_name      text not null default '',
  screenshot_path text,
  status          text not null default 'pending' check (status in ('pending','approved','rejected')),
  reject_reason   text,
  source          text not null default 'online' check (source in ('online','manual')),
  created_at      timestamptz not null default now(),
  approved_at     timestamptz
);
create index if not exists orders_status_idx  on public.orders (status, created_at desc);
create index if not exists orders_type_idx    on public.orders (type_id, status);
create index if not exists orders_email_idx   on public.orders (lower(email), status);

-- ---------- tickets (one per person) ----------
create table if not exists public.tickets (
  id            bigint generated by default as identity primary key,
  order_id      bigint not null references public.orders(id) on delete cascade,
  code          text not null unique,
  attendee_name text not null,
  used          boolean not null default false,
  used_at       timestamptz,
  used_by       text
);
create index if not exists tickets_order_idx on public.tickets (order_id);

-- ---------- email_log ----------
create table if not exists public.email_log (
  id         bigint generated by default as identity primary key,
  order_id   bigint references public.orders(id) on delete cascade,
  kind       text not null check (kind in ('received','approved','rejected','resent')),
  to_email   text not null,
  status     text not null check (status in ('sent','failed')),
  error      text,
  created_at timestamptz not null default now()
);
create index if not exists email_log_order_idx on public.email_log (order_id, created_at desc);
create index if not exists email_log_time_idx  on public.email_log (created_at desc);

-- ---------- scan_log ----------
create table if not exists public.scan_log (
  id         bigint generated by default as identity primary key,
  code       text,
  result     text not null,
  scanned_by text,
  undone     boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists scan_log_time_idx on public.scan_log (created_at desc);
