-- 01_schema.sql : tables, constraints, indexes. Safe to re-run.
-- Run order: 01 -> 02 -> 03 -> 04 -> 05 (then 06 once, after creating your admin user)

create extension if not exists pgcrypto;

-- ---------- event_settings (single row) ----------
create table if not exists public.event_settings (
  id                   int primary key default 1 check (id = 1),
  name                 text not null default 'My Event',
  date_text            text not null default '',
  venue                text not null default '',
  description          text not null default '',
  contact_phone        text not null default '',
  contact_email        text not null default '',
  payment_instructions text not null default '',
  terms_text           text not null default '',
  sales_open           boolean not null default false,
  sales_start          timestamptz,
  sales_end            timestamptz,
  closed_message       text not null default 'Ticket sales are closed.',
  max_per_order        int not null default 5 check (max_per_order between 1 and 50),
  logo_path            text,
  banner_path          text,
  theme                jsonb not null default '{}'::jsonb,
  ticket_design        jsonb not null default '{}'::jsonb,
  email_templates      jsonb not null default '{}'::jsonb,
  updated_at           timestamptz not null default now()
);
-- one UPI payment QR for the whole event (shown for every ticket type)
alter table public.event_settings add column if not exists payment_qr_path text;

-- ---------- ticket_types ----------
create table if not exists public.ticket_types (
  id              bigint generated by default as identity primary key,
  name            text not null,
  description     text not null default '',
  price           int  not null default 0 check (price >= 0),
  capacity        int  not null default 0 check (capacity >= 0),
  payment_qr_path text,
  accent_color    text,
  active          boolean not null default true,
  sort_order      int not null default 0,
  created_at      timestamptz not null default now()
);

-- ---------- orders ----------
create sequence if not exists public.order_no_seq start 1001;

create table if not exists public.orders (
  id              bigint generated by default as identity primary key,
  order_no        text not null unique,
  token           text not null unique,
  type_id         bigint not null references public.ticket_types(id) on delete restrict,
  type_name       text not null,
  unit_price      int  not null,
  qty             int  not null check (qty > 0),
  amount          int  not null check (amount >= 0),
  buyer_name      text not null,
  email           text not null,
  phone           text not null default '',
  payer_name      text not null default '',
  screenshot_path text,
  status          text not null default 'pending' check (status in ('pending','approved','rejected')),
  reject_reason   text,
  source          text not null default 'online' check (source in ('online','manual')),
  created_at      timestamptz not null default now(),
  approved_at     timestamptz
);
create index if not exists orders_status_idx  on public.orders (status, created_at desc);
create index if not exists orders_type_idx    on public.orders (type_id, status);
create index if not exists orders_email_idx   on public.orders (lower(email), status);

-- ---------- tickets (one per person) ----------
create table if not exists public.tickets (
  id            bigint generated by default as identity primary key,
  order_id      bigint not null references public.orders(id) on delete cascade,
  code          text not null unique,
  attendee_name text not null,
  used          boolean not null default false,
  used_at       timestamptz,
  used_by       text
);
create index if not exists tickets_order_idx on public.tickets (order_id);

-- ---------- email_log ----------
create table if not exists public.email_log (
  id         bigint generated by default as identity primary key,
  order_id   bigint references public.orders(id) on delete cascade,
  kind       text not null check (kind in ('received','approved','rejected','resent')),
  to_email   text not null,
  status     text not null check (status in ('sent','failed')),
  error      text,
  created_at timestamptz not null default now()
);
create index if not exists email_log_order_idx on public.email_log (order_id, created_at desc);
create index if not exists email_log_time_idx  on public.email_log (created_at desc);

-- ---------- scan_log ----------
create table if not exists public.scan_log (
  id         bigint generated by default as identity primary key,
  code       text,
  result     text not null,
  scanned_by text,
  undone     boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists scan_log_time_idx on public.scan_log (created_at desc);

-- ===== v2: one QR per order (admits the whole group), Aadhaar image per person, instructions panel =====
-- From v2 the QR code lives on the order (orders.ticket_code). tickets = one row per PERSON on the order.
alter table public.event_settings add column if not exists instructions_text text not null default '';
alter table public.orders  add column if not exists ticket_code   text;
alter table public.orders  add column if not exists checked_in    boolean not null default false;
alter table public.orders  add column if not exists checked_in_at timestamptz;
alter table public.orders  add column if not exists checked_in_by text;
create unique index if not exists orders_ticket_code_key on public.orders (ticket_code);
alter table public.tickets add column if not exists id_path text;        -- Aadhaar image, private bucket "ids"
alter table public.tickets alter column code drop not null;              -- per-person codes are no longer used

-- carry over orders made before v2: the first person's code becomes the order's QR code,
-- and an order counts as checked in if any of its people were already scanned
update public.orders o
   set ticket_code = (select t.code from public.tickets t where t.order_id = o.id and t.code is not null order by t.id limit 1)
 where o.ticket_code is null;
update public.orders o
   set checked_in = true,
       checked_in_at = (select max(t.used_at) from public.tickets t where t.order_id = o.id and t.used)
 where not o.checked_in and exists (select 1 from public.tickets t where t.order_id = o.id and t.used);
update public.tickets t
   set used = true, used_at = coalesce(t.used_at, o.checked_in_at), used_by = coalesce(t.used_by, o.checked_in_by)
  from public.orders o
 where o.id = t.order_id and o.checked_in and not t.used;

-- ===== v3: passes for several people (couple pass), one payment QR per amount, UPI ID, dandiya rental =====
alter table public.ticket_types add column if not exists persons_per_unit int not null default 1;
alter table public.ticket_types add column if not exists person_labels   text[] not null default '{}';   -- e.g. {Male,Female}
alter table public.ticket_types add column if not exists unit_label      text not null default '';        -- e.g. Couple
alter table public.ticket_types add column if not exists payment_qrs     jsonb not null default '{}'::jsonb; -- {"1":"path","2":"path",...}
do $$ begin
  alter table public.ticket_types add constraint ticket_types_ppu_chk check (persons_per_unit between 1 and 4);
exception when duplicate_object then null; end $$;

alter table public.event_settings add column if not exists upi_id          text not null default '';
alter table public.event_settings add column if not exists dandiya_enabled boolean not null default false;
alter table public.event_settings add column if not exists dandiya_rent    int not null default 50;
alter table public.event_settings add column if not exists dandiya_deposit int not null default 50;
alter table public.event_settings add column if not exists dandiya_max     int not null default 10;
alter table public.event_settings add column if not exists dandiya_qrs     jsonb not null default '{}'::jsonb;  -- {"1":"path",...}

alter table public.tickets add column if not exists slot text;   -- e.g. "Couple 1 · Male"

-- venue map; staff booking (secret link, discount, max people per staff member matched by mobile or email)
alter table public.event_settings add column if not exists venue_map        text not null default '';   -- Google Maps link or address
alter table public.event_settings add column if not exists staff_enabled    boolean not null default false;
alter table public.event_settings add column if not exists staff_discount   int not null default 20;      -- percent off every pass
alter table public.event_settings add column if not exists staff_max_people int not null default 2;
alter table public.event_settings add column if not exists staff_key        text not null default '';     -- secret in the staff link; never readable by buyers
alter table public.event_settings add column if not exists staff_qrs        jsonb not null default '{}'::jsonb;  -- {"240":"path","480":"path"}
do $$ begin
  alter table public.event_settings add constraint es_staff_discount_chk check (staff_discount between 0 and 90);
exception when duplicate_object then null; end $$;
do $$ begin
  alter table public.event_settings add constraint es_staff_max_chk check (staff_max_people between 1 and 20);
exception when duplicate_object then null; end $$;
alter table public.orders add column if not exists is_staff boolean not null default false;

-- group prices: total for N passes in one order, e.g. {"2":550,"3":807}. Missing N = price x N.
alter table public.ticket_types add column if not exists group_prices jsonb not null default '{}'::jsonb;

create table if not exists public.dandiya_rentals (
  id               bigint generated by default as identity primary key,
  order_id         bigint not null references public.orders(id) on delete cascade,
  pairs            int not null check (pairs between 1 and 50),
  amount           int not null check (amount >= 0),
  payer_name       text not null,
  screenshot_path  text,
  status           text not null default 'pending' check (status in ('pending','approved','rejected')),
  reject_reason    text,
  deposit_refunded boolean not null default false,
  created_at       timestamptz not null default now(),
  approved_at      timestamptz
);
create index if not exists dandiya_order_idx on public.dandiya_rentals (order_id, id desc);
create index if not exists dandiya_status_idx on public.dandiya_rentals (status, created_at desc);
