-- 09_upgrade_v3.sql : ONE file to upgrade an existing setup (paste & run once in the Supabase SQL editor).
-- Adds: passes for several people (Couple Pass), one payment QR per amount, UPI ID, dandiya rental.
-- Safe to re-run. Existing orders and tickets are unchanged.

-- ===== v3: passes for several people (couple pass), one payment QR per amount, UPI ID, dandiya rental =====
alter table public.ticket_types add column if not exists persons_per_unit int not null default 1;
alter table public.ticket_types add column if not exists person_labels   text[] not null default '{}';   -- e.g. {Male,Female}
alter table public.ticket_types add column if not exists unit_label      text not null default '';        -- e.g. Couple
alter table public.ticket_types add column if not exists payment_qrs     jsonb not null default '{}'::jsonb; -- {"1":"path","2":"path",...}
do $$ begin
  alter table public.ticket_types add constraint ticket_types_ppu_chk check (persons_per_unit between 1 and 4);
exception when duplicate_object then null; end $$;

alter table public.event_settings add column if not exists upi_id          text not null default '';
alter table public.event_settings add column if not exists dandiya_enabled boolean not null default false;
alter table public.event_settings add column if not exists dandiya_rent    int not null default 50;
alter table public.event_settings add column if not exists dandiya_deposit int not null default 50;
alter table public.event_settings add column if not exists dandiya_max     int not null default 10;
alter table public.event_settings add column if not exists dandiya_qrs     jsonb not null default '{}'::jsonb;  -- {"1":"path",...}

alter table public.tickets add column if not exists slot text;   -- e.g. "Couple 1 · Male"

create table if not exists public.dandiya_rentals (
  id               bigint generated by default as identity primary key,
  order_id         bigint not null references public.orders(id) on delete cascade,
  pairs            int not null check (pairs between 1 and 50),
  amount           int not null check (amount >= 0),
  payer_name       text not null,
  screenshot_path  text,
  status           text not null default 'pending' check (status in ('pending','approved','rejected')),
  reject_reason    text,
  deposit_refunded boolean not null default false,
  created_at       timestamptz not null default now(),
  approved_at      timestamptz
);
create index if not exists dandiya_order_idx on public.dandiya_rentals (order_id, id desc);
create index if not exists dandiya_status_idx on public.dandiya_rentals (status, created_at desc);

-- ===== v3 grants =====
grant select (upi_id, dandiya_enabled, dandiya_rent, dandiya_deposit, dandiya_max, dandiya_qrs)
  on public.event_settings to anon, authenticated;
grant select (persons_per_unit, person_labels, unit_label, payment_qrs) on public.ticket_types to anon;

alter table public.dandiya_rentals enable row level security;
grant select on public.dandiya_rentals to authenticated;
grant update (deposit_refunded) on public.dandiya_rentals to authenticated;
drop policy if exists dandiya_admin_read on public.dandiya_rentals;
create policy dandiya_admin_read on public.dandiya_rentals for select to authenticated using (public.is_admin());
drop policy if exists dandiya_admin_upd on public.dandiya_rentals;
create policy dandiya_admin_upd on public.dandiya_rentals for update to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- ---------- public: ticket types with seats left (v3: people per pass, per-amount QRs) ----------
drop function if exists public.public_ticket_types();   -- return columns changed in v3
create or replace function public.public_ticket_types()
returns table (id bigint, name text, description text, price int, capacity int,
               payment_qr_path text, accent_color text, sort_order int, remaining int,
               persons_per_unit int, person_labels text[], unit_label text, payment_qrs jsonb)
language sql stable security definer set search_path = public, pg_temp as $$
  select t.id, t.name, t.description, t.price, t.capacity, t.payment_qr_path, t.accent_color,
         t.sort_order, greatest(t.capacity - public._seats_taken(t.id), 0),
         t.persons_per_unit, t.person_labels, t.unit_label, t.payment_qrs
  from public.ticket_types t
  where t.active
  order by t.sort_order, t.id;
$$;
revoke all on function public.public_ticket_types() from public, anon, authenticated;
grant execute on function public.public_ticket_types() to anon, authenticated;

-- label of person k (1-based) in pass u, e.g. "Couple 2 · Female" or "Female"
create or replace function public._slot_label(t public.ticket_types, u int, k int) returns text
language sql immutable set search_path = public, pg_temp as $$
  select case when t.persons_per_unit > 1
              then coalesce(nullif(t.unit_label, ''), 'Group') || ' ' || u || ' · ' || coalesce(t.person_labels[k], 'Person ' || k)
              else coalesce(t.person_labels[1], '') end;
$$;
revoke all on function public._slot_label(public.ticket_types,int,int) from public, anon, authenticated;

-- ---------- public: create_order ----------
-- Price comes from ticket_types, never the client. Errors are plain codes the page maps to messages.
-- One QR code per order (admits everyone on it); qty = passes; people = qty x persons_per_unit,
-- each with a name and an Aadhaar image.
drop function if exists public.create_order(bigint,int,text,text,text,text,text,text[]);   -- pre-v2 signature (no Aadhaar)
create or replace function public.create_order(
  p_type_id bigint, p_qty int, p_buyer_name text, p_email text, p_phone text,
  p_payer_name text, p_screenshot_path text, p_names text[], p_id_paths text[]
) returns text
language plpgsql security definer set search_path = public, extensions, pg_temp as $$
declare
  s   public.event_settings%rowtype;
  t   public.ticket_types%rowtype;
  v_email text := lower(btrim(coalesce(p_email, '')));
  v_name  text := btrim(coalesce(p_buyer_name, ''));
  v_payer text := btrim(coalesce(p_payer_name, ''));
  v_phone text := btrim(coalesce(p_phone, ''));
  v_order public.orders%rowtype;
  v_left  int; v_people int; i int; nm text;
begin
  select * into s from public.event_settings where id = 1;
  if not found or not s.sales_open
     or (s.sales_start is not null and now() < s.sales_start)
     or (s.sales_end   is not null and now() > s.sales_end) then
    raise exception 'SALES_CLOSED';
  end if;

  if p_qty is null or p_qty < 1 then raise exception 'BAD_QTY'; end if;
  if p_qty > s.max_per_order then raise exception 'MAX_PER_ORDER:%', s.max_per_order; end if;
  if length(v_name) < 2 or length(v_name) > 80 then raise exception 'BAD_NAME'; end if;
  if length(regexp_replace(v_phone, '\D', '', 'g')) < 10 or length(v_phone) > 20 then raise exception 'BAD_PHONE'; end if;
  if v_email !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' or length(v_email) > 120 then raise exception 'BAD_EMAIL'; end if;
  if length(v_payer) < 2 or length(v_payer) > 80 then raise exception 'BAD_PAYER'; end if;

  -- Lock the ticket type row: concurrent buyers of this type queue here, so seats cannot be oversold.
  select * into t from public.ticket_types where id = p_type_id and active for update;
  if not found then raise exception 'TYPE_UNAVAILABLE'; end if;
  v_people := p_qty * t.persons_per_unit;

  if p_names is null or coalesce(array_length(p_names, 1), 0) <> v_people then raise exception 'BAD_ATTENDEES'; end if;
  foreach nm in array p_names loop
    if length(btrim(coalesce(nm, ''))) < 2 or length(nm) > 80 then raise exception 'BAD_ATTENDEES'; end if;
  end loop;

  -- one Aadhaar image per person: uploaded through the public uploader, all different, never used before
  if p_id_paths is null or coalesce(array_length(p_id_paths, 1), 0) <> v_people
     or (select count(distinct x) from unnest(p_id_paths) x) <> v_people then
    raise exception 'BAD_IDS';
  end if;
  for i in 1..v_people loop
    if p_id_paths[i] is null or p_id_paths[i] !~ '^[0-9a-f-]{36}\.jpg$'
       or not exists (select 1 from storage.objects o where o.bucket_id = 'ids' and o.name = p_id_paths[i])
       or exists (select 1 from public.tickets where id_path = p_id_paths[i]) then
      raise exception 'BAD_IDS:%', i;
    end if;
  end loop;

  -- screenshot must be a path uploaded through the public uploader and not used anywhere else
  if p_screenshot_path is null or p_screenshot_path !~ '^[0-9a-f-]{36}\.jpg$'
     or not exists (select 1 from storage.objects o where o.bucket_id = 'screenshots' and o.name = p_screenshot_path)
     or exists (select 1 from public.orders where screenshot_path = p_screenshot_path)
     or exists (select 1 from public.dandiya_rentals where screenshot_path = p_screenshot_path) then
    raise exception 'BAD_SCREENSHOT';
  end if;

  v_left := t.capacity - public._seats_taken(t.id);
  if v_left <= 0 then raise exception 'SOLD_OUT'; end if;
  if p_qty > v_left then raise exception 'NOT_ENOUGH_SEATS:%', v_left; end if;

  if (select count(*) from public.orders where lower(email) = v_email and status = 'pending') >= 3 then
    raise exception 'TOO_MANY_PENDING';
  end if;

  insert into public.orders (order_no, token, ticket_code, type_id, type_name, unit_price, qty, amount,
                             buyer_name, email, phone, payer_name, screenshot_path, status, source)
  values ('ORD-' || nextval('public.order_no_seq'), public._rand_token(), public._new_ticket_code(), t.id, t.name, t.price, p_qty,
          t.price * p_qty, v_name, v_email, v_phone, v_payer, p_screenshot_path, 'pending', 'online')
  returning * into v_order;

  for i in 1..v_people loop
    insert into public.tickets (order_id, attendee_name, id_path, slot)
    values (v_order.id, btrim(p_names[i]), p_id_paths[i],
            public._slot_label(t, (i - 1) / t.persons_per_unit + 1, (i - 1) % t.persons_per_unit + 1));
  end loop;

  return v_order.token;
end $$;
revoke all on function public.create_order(bigint,int,text,text,text,text,text,text[],text[]) from public, anon, authenticated;
grant execute on function public.create_order(bigint,int,text,text,text,text,text,text[],text[]) to anon, authenticated;

-- ---------- public: get_order (by unguessable token) ----------
-- Names (+ slot labels), the QR code only once approved, and the latest dandiya rental. Never IDs or screenshots.
create or replace function public.get_order(p_token text) returns jsonb
language plpgsql stable security definer set search_path = public, pg_temp as $$
declare o public.orders%rowtype; d public.dandiya_rentals%rowtype;
begin
  if p_token is null or length(p_token) <> 24 then return null; end if;
  select * into o from public.orders where token = p_token;
  if not found then return null; end if;
  select * into d from public.dandiya_rentals where order_id = o.id order by id desc limit 1;
  return jsonb_build_object(
    'order_no', o.order_no, 'status', o.status, 'reject_reason', o.reject_reason,
    'type_id', o.type_id, 'type_name', o.type_name, 'qty', o.qty, 'amount', o.amount,
    'buyer_name', o.buyer_name, 'email', o.email, 'created_at', o.created_at,
    'accent_color', (select accent_color from public.ticket_types where id = o.type_id),
    'people', (select coalesce(jsonb_agg(attendee_name order by id), '[]'::jsonb) from public.tickets where order_id = o.id),
    'slots',  (select coalesce(jsonb_agg(coalesce(slot, '') order by id), '[]'::jsonb) from public.tickets where order_id = o.id),
    'code', case when o.status = 'approved' then o.ticket_code end,
    'checked_in', o.checked_in,
    'dandiya', case when d.id is null then null else jsonb_build_object(
        'pairs', d.pairs, 'amount', d.amount, 'status', d.status, 'reject_reason', d.reject_reason,
        'deposit_refunded', d.deposit_refunded, 'created_at', d.created_at) end);
end $$;
revoke all on function public.get_order(text) from public, anon, authenticated;
grant execute on function public.get_order(text) to anon, authenticated;

-- ---------- public: request a dandiya rental for an approved order ----------
create or replace function public.request_dandiya(p_token text, p_pairs int, p_payer_name text, p_screenshot_path text)
returns jsonb language plpgsql security definer set search_path = public, pg_temp as $$
declare s public.event_settings%rowtype; o public.orders%rowtype; v_payer text := btrim(coalesce(p_payer_name, ''));
begin
  select * into s from public.event_settings where id = 1;
  if not s.dandiya_enabled then raise exception 'DANDIYA_OFF'; end if;
  if p_token is null or length(p_token) <> 24 then raise exception 'NOT_FOUND'; end if;
  select * into o from public.orders where token = p_token for update;
  if not found then raise exception 'NOT_FOUND'; end if;
  if o.status <> 'approved' then raise exception 'ORDER_NOT_APPROVED'; end if;
  if exists (select 1 from public.dandiya_rentals where order_id = o.id and status in ('pending','approved')) then
    raise exception 'DANDIYA_EXISTS';
  end if;
  if p_pairs is null or p_pairs < 1 or p_pairs > s.dandiya_max then raise exception 'BAD_PAIRS:%', s.dandiya_max; end if;
  if length(v_payer) < 2 or length(v_payer) > 80 then raise exception 'BAD_PAYER'; end if;
  if p_screenshot_path is null or p_screenshot_path !~ '^[0-9a-f-]{36}\.jpg$'
     or not exists (select 1 from storage.objects x where x.bucket_id = 'screenshots' and x.name = p_screenshot_path)
     or exists (select 1 from public.orders where screenshot_path = p_screenshot_path)
     or exists (select 1 from public.dandiya_rentals where screenshot_path = p_screenshot_path) then
    raise exception 'BAD_SCREENSHOT';
  end if;
  insert into public.dandiya_rentals (order_id, pairs, amount, payer_name, screenshot_path)
  values (o.id, p_pairs, p_pairs * (s.dandiya_rent + s.dandiya_deposit), v_payer, p_screenshot_path);
  return jsonb_build_object('ok', true);
end $$;
revoke all on function public.request_dandiya(text,int,text,text) from public, anon, authenticated;
grant execute on function public.request_dandiya(text,int,text,text) to anon, authenticated;

-- ---------- admin: approve / reject a dandiya rental ----------
create or replace function public.admin_set_dandiya_status(p_id bigint, p_status text, p_reason text default null)
returns jsonb language plpgsql security definer set search_path = public, pg_temp as $$
declare d public.dandiya_rentals%rowtype;
begin
  if not public.is_admin() then raise exception 'FORBIDDEN'; end if;
  if p_status not in ('pending','approved','rejected') then raise exception 'BAD_STATUS'; end if;
  select * into d from public.dandiya_rentals where id = p_id for update;
  if not found then raise exception 'NOT_FOUND'; end if;
  update public.dandiya_rentals set
    status = p_status,
    reject_reason = case when p_status = 'rejected' then nullif(btrim(coalesce(p_reason, '')), '') else null end,
    approved_at   = case when p_status = 'approved' then now() else null end
  where id = d.id returning * into d;
  return to_jsonb(d) - 'screenshot_path';
end $$;
revoke all on function public.admin_set_dandiya_status(bigint,text,text) from public, anon, authenticated;
grant execute on function public.admin_set_dandiya_status(bigint,text,text) to authenticated;

-- ---------- admin: manual order (cash / complimentary). Issued as approved. ----------
create or replace function public.admin_create_manual_order(
  p_type_id bigint, p_qty int, p_buyer_name text, p_email text, p_phone text,
  p_names text[], p_amount int default null
) returns jsonb language plpgsql security definer set search_path = public, extensions, pg_temp as $$
declare t public.ticket_types%rowtype; o public.orders%rowtype; i int; nm text; v_people int;
        v_email text := lower(btrim(coalesce(p_email, '')));
begin
  if not public.is_admin() then raise exception 'FORBIDDEN'; end if;
  if p_qty is null or p_qty < 1 or p_qty > 50 then raise exception 'BAD_QTY'; end if;
  if length(btrim(coalesce(p_buyer_name, ''))) < 2 then raise exception 'BAD_NAME'; end if;
  if v_email !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' then raise exception 'BAD_EMAIL'; end if;
  if p_amount is not null and p_amount < 0 then raise exception 'BAD_AMOUNT'; end if;

  select * into t from public.ticket_types where id = p_type_id for update;
  if not found then raise exception 'TYPE_UNAVAILABLE'; end if;
  v_people := p_qty * t.persons_per_unit;
  if p_names is null or coalesce(array_length(p_names, 1), 0) <> v_people then raise exception 'BAD_ATTENDEES'; end if;
  foreach nm in array p_names loop
    if length(btrim(coalesce(nm, ''))) < 2 then raise exception 'BAD_ATTENDEES'; end if;
  end loop;
  if p_qty > t.capacity - public._seats_taken(t.id) then
    raise exception 'NOT_ENOUGH_SEATS:%', greatest(t.capacity - public._seats_taken(t.id), 0);
  end if;

  insert into public.orders (order_no, token, ticket_code, type_id, type_name, unit_price, qty, amount, buyer_name, email,
                             phone, payer_name, status, source, approved_at)
  values ('ORD-' || nextval('public.order_no_seq'), public._rand_token(), public._new_ticket_code(), t.id, t.name, t.price, p_qty,
          coalesce(p_amount, t.price * p_qty), btrim(p_buyer_name), v_email, btrim(coalesce(p_phone, '')),
          'manual', 'approved', 'manual', now())
  returning * into o;
  for i in 1..v_people loop
    insert into public.tickets (order_id, attendee_name, slot)
    values (o.id, btrim(p_names[i]), public._slot_label(t, (i - 1) / t.persons_per_unit + 1, (i - 1) % t.persons_per_unit + 1));
  end loop;
  return jsonb_build_object('order_id', o.id, 'order_no', o.order_no, 'token', o.token);
end $$;
revoke all on function public.admin_create_manual_order(bigint,int,text,text,text,text[],int) from public, anon, authenticated;
grant execute on function public.admin_create_manual_order(bigint,int,text,text,text,text[],int) to authenticated;

-- ---------- scanner: check_in / undo / stats / recent ----------
-- One QR per order: a valid scan admits everyone on the order at once.
-- Returns result + names (array) + count + type_name (+ used_at when already used) + paid dandiya pairs.
create or replace function public.check_in(p_code text) returns jsonb
language plpgsql security definer set search_path = public, pg_temp as $$
declare
  v_code  text := upper(btrim(coalesce(p_code, '')));
  v_who   text := coalesce(auth.jwt() ->> 'email', 'unknown');
  v_id    bigint; o public.orders%rowtype; v_names jsonb; v_pairs int;
begin
  if not public.is_staff() then raise exception 'FORBIDDEN'; end if;
  v_id := public._order_for_code(v_code);
  if v_id is null then
    insert into public.scan_log (code, result, scanned_by) values (left(v_code, 40), 'invalid', v_who);
    return jsonb_build_object('result', 'invalid');
  end if;
  select * into o from public.orders where id = v_id;
  select coalesce(jsonb_agg(attendee_name order by id), '[]'::jsonb) into v_names from public.tickets where order_id = o.id;
  select coalesce(sum(pairs), 0)::int into v_pairs from public.dandiya_rentals where order_id = o.id and status = 'approved';

  if o.status <> 'approved' then
    insert into public.scan_log (code, result, scanned_by) values (v_code, 'not_valid', v_who);
    return jsonb_build_object('result', 'not_valid', 'names', v_names, 'count', jsonb_array_length(v_names), 'type_name', o.type_name);
  end if;

  update public.orders set checked_in = true, checked_in_at = now(), checked_in_by = v_who
   where id = o.id and checked_in = false
   returning * into o;
  if found then
    update public.tickets set used = true, used_at = o.checked_in_at, used_by = v_who where order_id = o.id;
    insert into public.scan_log (code, result, scanned_by) values (v_code, 'ok', v_who);
    return jsonb_build_object('result', 'ok', 'names', v_names, 'count', jsonb_array_length(v_names),
                              'type_name', o.type_name, 'order_no', o.order_no, 'code', v_code, 'used_at', o.checked_in_at,
                              'dandiya_pairs', v_pairs);
  end if;
  select * into o from public.orders where id = v_id;
  insert into public.scan_log (code, result, scanned_by) values (v_code, 'already_used', v_who);
  return jsonb_build_object('result', 'already_used', 'names', v_names, 'count', jsonb_array_length(v_names),
                            'type_name', o.type_name, 'order_no', o.order_no, 'code', v_code, 'used_at', o.checked_in_at,
                            'dandiya_pairs', v_pairs);
end $$;
revoke all on function public.check_in(text) from public, anon, authenticated;
grant execute on function public.check_in(text) to authenticated;

-- v3: the two passes (added switched OFF; set seats and payment QRs in Admin > Ticket types, then turn them on)
insert into public.ticket_types (name, description, price, capacity, active, sort_order, persons_per_unit, person_labels, unit_label)
select 'Female Solo', 'One pass per woman', 300, 100, false, 10, 1, '{Female}', ''
where not exists (select 1 from public.ticket_types where name = 'Female Solo');
insert into public.ticket_types (name, description, price, capacity, active, sort_order, persons_per_unit, person_labels, unit_label)
select 'Couple Pass', 'One pass admits a couple', 600, 100, false, 20, 2, '{Male,Female}', 'Couple'
where not exists (select 1 from public.ticket_types where name = 'Couple Pass');
