-- 14_upgrade_v4.sql : ONE file to bring an existing setup fully up to date (paste & run once in the Supabase SQL editor).
-- Includes everything from 10-13 (venue map, no Aadhaar, staff booking) plus v4:
--   * General Pass ₹300 with group prices (2 = ₹550, 3 = ₹807, 4 = ₹1052, 5 = ₹1285), up to 5 on one QR
--   * each person marked Student (girls of the school; consent form at school) or Parent / Guest
--   * offline (cash) orders without an email address
-- It re-applies 01_schema, 02_rls and 03_rpc (all safe to re-run), then sets up the passes at the bottom.
-- Safe to re-run. Existing orders and tickets are unchanged.

-- ================================ sql/01_schema.sql ================================
-- 01_schema.sql : tables, constraints, indexes. Safe to re-run.
-- Run order: 01 -> 02 -> 03 -> 04 -> 05 (then 06 once, after creating your admin user)

create extension if not exists pgcrypto;

-- ---------- event_settings (single row) ----------
create table if not exists public.event_settings (
  id                   int primary key default 1 check (id = 1),
  name                 text not null default 'My Event',
  date_text            text not null default '',
  venue                text not null default '',
  description          text not null default '',
  contact_phone        text not null default '',
  contact_email        text not null default '',
  payment_instructions text not null default '',
  terms_text           text not null default '',
  sales_open           boolean not null default false,
  sales_start          timestamptz,
  sales_end            timestamptz,
  closed_message       text not null default 'Ticket sales are closed.',
  max_per_order        int not null default 5 check (max_per_order between 1 and 50),
  logo_path            text,
  banner_path          text,
  theme                jsonb not null default '{}'::jsonb,
  ticket_design        jsonb not null default '{}'::jsonb,
  email_templates      jsonb not null default '{}'::jsonb,
  updated_at           timestamptz not null default now()
);
-- one UPI payment QR for the whole event (shown for every ticket type)
alter table public.event_settings add column if not exists payment_qr_path text;

-- ---------- ticket_types ----------
create table if not exists public.ticket_types (
  id              bigint generated by default as identity primary key,
  name            text not null,
  description     text not null default '',
  price           int  not null default 0 check (price >= 0),
  capacity        int  not null default 0 check (capacity >= 0),
  payment_qr_path text,
  accent_color    text,
  active          boolean not null default true,
  sort_order      int not null default 0,
  created_at      timestamptz not null default now()
);

-- ---------- orders ----------
create sequence if not exists public.order_no_seq start 1001;

create table if not exists public.orders (
  id              bigint generated by default as identity primary key,
  order_no        text not null unique,
  token           text not null unique,
  type_id         bigint not null references public.ticket_types(id) on delete restrict,
  type_name       text not null,
  unit_price      int  not null,
  qty             int  not null check (qty > 0),
  amount          int  not null check (amount >= 0),
  buyer_name      text not null,
  email           text not null,
  phone           text not null default '',
  payer_name      text not null default '',
  screenshot_path text,
  status          text not null default 'pending' check (status in ('pending','approved','rejected')),
  reject_reason   text,
  source          text not null default 'online' check (source in ('online','manual')),
  created_at      timestamptz not null default now(),
  approved_at     timestamptz
);
create index if not exists orders_status_idx  on public.orders (status, created_at desc);
create index if not exists orders_type_idx    on public.orders (type_id, status);
create index if not exists orders_email_idx   on public.orders (lower(email), status);

-- ---------- tickets (one per person) ----------
create table if not exists public.tickets (
  id            bigint generated by default as identity primary key,
  order_id      bigint not null references public.orders(id) on delete cascade,
  code          text not null unique,
  attendee_name text not null,
  used          boolean not null default false,
  used_at       timestamptz,
  used_by       text
);
create index if not exists tickets_order_idx on public.tickets (order_id);

-- ---------- email_log ----------
create table if not exists public.email_log (
  id         bigint generated by default as identity primary key,
  order_id   bigint references public.orders(id) on delete cascade,
  kind       text not null check (kind in ('received','approved','rejected','resent')),
  to_email   text not null,
  status     text not null check (status in ('sent','failed')),
  error      text,
  created_at timestamptz not null default now()
);
create index if not exists email_log_order_idx on public.email_log (order_id, created_at desc);
create index if not exists email_log_time_idx  on public.email_log (created_at desc);

-- ---------- scan_log ----------
create table if not exists public.scan_log (
  id         bigint generated by default as identity primary key,
  code       text,
  result     text not null,
  scanned_by text,
  undone     boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists scan_log_time_idx on public.scan_log (created_at desc);

-- ===== v2: one QR per order (admits the whole group), Aadhaar image per person, instructions panel =====
-- From v2 the QR code lives on the order (orders.ticket_code). tickets = one row per PERSON on the order.
alter table public.event_settings add column if not exists instructions_text text not null default '';
alter table public.orders  add column if not exists ticket_code   text;
alter table public.orders  add column if not exists checked_in    boolean not null default false;
alter table public.orders  add column if not exists checked_in_at timestamptz;
alter table public.orders  add column if not exists checked_in_by text;
create unique index if not exists orders_ticket_code_key on public.orders (ticket_code);
alter table public.tickets add column if not exists id_path text;        -- Aadhaar image, private bucket "ids"
alter table public.tickets alter column code drop not null;              -- per-person codes are no longer used

-- carry over orders made before v2: the first person's code becomes the order's QR code,
-- and an order counts as checked in if any of its people were already scanned
update public.orders o
   set ticket_code = (select t.code from public.tickets t where t.order_id = o.id and t.code is not null order by t.id limit 1)
 where o.ticket_code is null;
update public.orders o
   set checked_in = true,
       checked_in_at = (select max(t.used_at) from public.tickets t where t.order_id = o.id and t.used)
 where not o.checked_in and exists (select 1 from public.tickets t where t.order_id = o.id and t.used);
update public.tickets t
   set used = true, used_at = coalesce(t.used_at, o.checked_in_at), used_by = coalesce(t.used_by, o.checked_in_by)
  from public.orders o
 where o.id = t.order_id and o.checked_in and not t.used;

-- ===== v3: passes for several people (couple pass), one payment QR per amount, UPI ID, dandiya rental =====
alter table public.ticket_types add column if not exists persons_per_unit int not null default 1;
alter table public.ticket_types add column if not exists person_labels   text[] not null default '{}';   -- e.g. {Male,Female}
alter table public.ticket_types add column if not exists unit_label      text not null default '';        -- e.g. Couple
alter table public.ticket_types add column if not exists payment_qrs     jsonb not null default '{}'::jsonb; -- {"1":"path","2":"path",...}
do $$ begin
  alter table public.ticket_types add constraint ticket_types_ppu_chk check (persons_per_unit between 1 and 4);
exception when duplicate_object then null; end $$;

alter table public.event_settings add column if not exists upi_id          text not null default '';
alter table public.event_settings add column if not exists dandiya_enabled boolean not null default false;
alter table public.event_settings add column if not exists dandiya_rent    int not null default 50;
alter table public.event_settings add column if not exists dandiya_deposit int not null default 50;
alter table public.event_settings add column if not exists dandiya_max     int not null default 10;
alter table public.event_settings add column if not exists dandiya_qrs     jsonb not null default '{}'::jsonb;  -- {"1":"path",...}

alter table public.tickets add column if not exists slot text;   -- e.g. "Couple 1 · Male"

-- venue map; staff booking (secret link, discount, max people per staff member matched by mobile or email)
alter table public.event_settings add column if not exists venue_map        text not null default '';   -- Google Maps link or address
alter table public.event_settings add column if not exists staff_enabled    boolean not null default false;
alter table public.event_settings add column if not exists staff_discount   int not null default 20;      -- percent off every pass
alter table public.event_settings add column if not exists staff_max_people int not null default 2;
alter table public.event_settings add column if not exists staff_key        text not null default '';     -- secret in the staff link; never readable by buyers
alter table public.event_settings add column if not exists staff_qrs        jsonb not null default '{}'::jsonb;  -- {"240":"path","480":"path"}
do $$ begin
  alter table public.event_settings add constraint es_staff_discount_chk check (staff_discount between 0 and 90);
exception when duplicate_object then null; end $$;
do $$ begin
  alter table public.event_settings add constraint es_staff_max_chk check (staff_max_people between 1 and 20);
exception when duplicate_object then null; end $$;
alter table public.orders add column if not exists is_staff boolean not null default false;

-- group prices: total for N passes in one order, e.g. {"2":550,"3":807}. Missing N = price x N.
alter table public.ticket_types add column if not exists group_prices jsonb not null default '{}'::jsonb;

-- students on a pass: the signed consent form must be received at school before the pass is issued
alter table public.orders add column if not exists consent_ok boolean not null default false;

-- link-preview image (WhatsApp etc.) uploaded in Admin > Event; served by the admin site's /api/og-image
alter table public.event_settings add column if not exists og_image_path text not null default '';

-- staff booking: child pass price (staff's own children; counts toward staff_max_people)
alter table public.event_settings add column if not exists staff_child_price int not null default 150;
alter table public.event_settings add column if not exists staff_max_children int not null default 1;   -- per staff member, across orders

create table if not exists public.dandiya_rentals (
  id               bigint generated by default as identity primary key,
  order_id         bigint not null references public.orders(id) on delete cascade,
  pairs            int not null check (pairs between 1 and 50),
  amount           int not null check (amount >= 0),
  payer_name       text not null,
  screenshot_path  text,
  status           text not null default 'pending' check (status in ('pending','approved','rejected')),
  reject_reason    text,
  deposit_refunded boolean not null default false,
  created_at       timestamptz not null default now(),
  approved_at      timestamptz
);
create index if not exists dandiya_order_idx on public.dandiya_rentals (order_id, id desc);
create index if not exists dandiya_status_idx on public.dandiya_rentals (status, created_at desc);

-- ================================ sql/02_rls.sql ================================
-- 02_rls.sql : lock everything down, then grant only what each role needs. Safe to re-run.
-- Roles: anon (public buyers) | authenticated with app_metadata.role = 'admin' | 'scanner'.

-- Helper checks. They also confirm the auth user still exists and is not banned,
-- so deleting a scanner login takes effect immediately (not after the JWT expires).
create or replace function public.is_admin() returns boolean
language sql stable security definer set search_path = public, pg_temp as $$
  select coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin'
     and exists (select 1 from auth.users u
                 where u.id = auth.uid() and u.deleted_at is null
                   and (u.banned_until is null or u.banned_until < now()));
$$;

create or replace function public.is_staff() returns boolean
language sql stable security definer set search_path = public, pg_temp as $$
  select coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') in ('admin','scanner')
     and exists (select 1 from auth.users u
                 where u.id = auth.uid() and u.deleted_at is null
                   and (u.banned_until is null or u.banned_until < now()));
$$;

revoke all on function public.is_admin() from public;
revoke all on function public.is_staff() from public;
grant execute on function public.is_admin() to anon, authenticated;
grant execute on function public.is_staff() to anon, authenticated;

-- Start from zero: nobody has anything unless granted below.
revoke all on all tables    in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
alter default privileges in schema public revoke all on tables    from anon, authenticated;
alter default privileges in schema public revoke all on sequences from anon, authenticated;
alter default privileges in schema public revoke all on functions from public, anon, authenticated;

alter table public.event_settings enable row level security;
alter table public.ticket_types   enable row level security;
alter table public.orders         enable row level security;
alter table public.tickets        enable row level security;
alter table public.email_log      enable row level security;
alter table public.scan_log       enable row level security;

-- ---------- event_settings ----------
-- Everyone may read the public columns. email_templates is NOT granted to anyone
-- (admin reads it through admin_get_email_templates(); functions use the service role).
grant select (id, name, date_text, venue, description, contact_phone, contact_email,
              payment_instructions, terms_text, sales_open, sales_start, sales_end,
              closed_message, max_per_order, logo_path, banner_path, payment_qr_path, instructions_text, theme, ticket_design, updated_at)
  on public.event_settings to anon, authenticated;
grant update on public.event_settings to authenticated;

drop policy if exists es_public_read on public.event_settings;
create policy es_public_read on public.event_settings for select to anon, authenticated using (true);
drop policy if exists es_admin_update on public.event_settings;
create policy es_admin_update on public.event_settings for update to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- ---------- ticket_types ----------
grant select (id, name, description, price, capacity, payment_qr_path, accent_color, active, sort_order)
  on public.ticket_types to anon;
grant select, insert, update, delete on public.ticket_types to authenticated;

drop policy if exists tt_public_read on public.ticket_types;
create policy tt_public_read on public.ticket_types for select to anon, authenticated using (active);
drop policy if exists tt_admin_all on public.ticket_types;
create policy tt_admin_all on public.ticket_types for all to authenticated
  using (public.is_admin()) with check (public.is_admin());
grant usage on sequence public.ticket_types_id_seq to authenticated;

-- ---------- orders / tickets / logs : admin read only (writes go through RPCs) ----------
grant select on public.orders, public.tickets, public.email_log, public.scan_log to authenticated;
grant update (email) on public.orders to authenticated;   -- "Edit email address"
grant update (consent_ok) on public.orders to authenticated;   -- "Consent form received" tick (admin only, by RLS)

drop policy if exists orders_admin_read on public.orders;
create policy orders_admin_read on public.orders for select to authenticated using (public.is_admin());
drop policy if exists orders_admin_upd on public.orders;
create policy orders_admin_upd on public.orders for update to authenticated
  using (public.is_admin()) with check (public.is_admin());
drop policy if exists tickets_admin_read on public.tickets;
create policy tickets_admin_read on public.tickets for select to authenticated using (public.is_admin());
drop policy if exists email_log_admin_read on public.email_log;
create policy email_log_admin_read on public.email_log for select to authenticated using (public.is_admin());
drop policy if exists scan_log_admin_read on public.scan_log;
create policy scan_log_admin_read on public.scan_log for select to authenticated using (public.is_admin());

-- ===== v3 grants =====
grant select (upi_id, dandiya_enabled, dandiya_rent, dandiya_deposit, dandiya_max, dandiya_qrs)
  on public.event_settings to anon, authenticated;
grant select (persons_per_unit, person_labels, unit_label, payment_qrs) on public.ticket_types to anon;
grant select (group_prices) on public.ticket_types to anon;
grant select (og_image_path) on public.event_settings to anon, authenticated;
grant select (staff_child_price, staff_max_children) on public.event_settings to anon, authenticated;

-- venue map + staff booking settings. staff_key is NOT granted: the admin reads it through admin_staff_key().
grant select (venue_map, staff_enabled, staff_discount, staff_max_people, staff_qrs)
  on public.event_settings to anon, authenticated;

alter table public.dandiya_rentals enable row level security;
grant select on public.dandiya_rentals to authenticated;
grant update (deposit_refunded) on public.dandiya_rentals to authenticated;
drop policy if exists dandiya_admin_read on public.dandiya_rentals;
create policy dandiya_admin_read on public.dandiya_rentals for select to authenticated using (public.is_admin());
drop policy if exists dandiya_admin_upd on public.dandiya_rentals;
create policy dandiya_admin_upd on public.dandiya_rentals for update to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- ===== Realtime: admin Orders tab updates instantly (RLS still applies: only admins receive rows) =====
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    begin alter publication supabase_realtime add table public.orders;          exception when duplicate_object then null; end;
    begin alter publication supabase_realtime add table public.dandiya_rentals; exception when duplicate_object then null; end;
  end if;
end $$;

-- ================================ sql/03_rpc.sql ================================
-- 03_rpc.sql : all business rules live here (security definer). Safe to re-run.

-- ---------- internal helpers (not callable by API roles) ----------
create or replace function public._rand_token() returns text
language sql volatile set search_path = public, extensions, pg_temp as $$
  select translate(encode(gen_random_bytes(18), 'base64'), '+/', 'ab');   -- 24 chars
$$;

create or replace function public._new_ticket_code() returns text
language plpgsql volatile set search_path = public, extensions, pg_temp as $$
declare
  alphabet constant text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';   -- no 0/O/1/I
  b bytea; c text; i int;
begin
  loop
    b := gen_random_bytes(10); c := 'TKT-';
    for i in 0..9 loop
      c := c || substr(alphabet, (get_byte(b, i) % 32) + 1, 1);
    end loop;
    exit when not exists (select 1 from public.orders where ticket_code = c)
          and not exists (select 1 from public.tickets where code = c);
  end loop;
  return c;
end $$;

-- QR code -> order id. Orders made before v2 also match by an old per-person code.
create or replace function public._order_for_code(p_code text) returns bigint
language sql stable set search_path = public, pg_temp as $$
  select coalesce((select id from public.orders where ticket_code = p_code),
                  (select order_id from public.tickets where code = p_code));
$$;

create or replace function public._seats_taken(p_type_id bigint) returns int
language sql stable set search_path = public, pg_temp as $$
  select coalesce(sum(qty), 0)::int from public.orders
  where type_id = p_type_id and status in ('pending','approved');
$$;

revoke all on function public._rand_token()        from public, anon, authenticated;
revoke all on function public._new_ticket_code()   from public, anon, authenticated;
revoke all on function public._seats_taken(bigint) from public, anon, authenticated;
revoke all on function public._order_for_code(text)  from public, anon, authenticated;

-- ---------- public: ticket types with seats left (v3: people per pass, per-amount QRs) ----------
drop function if exists public.public_ticket_types();   -- return columns changed (v3, group prices)
create or replace function public.public_ticket_types()
returns table (id bigint, name text, description text, price int, capacity int,
               payment_qr_path text, accent_color text, sort_order int, remaining int,
               persons_per_unit int, person_labels text[], unit_label text, payment_qrs jsonb, group_prices jsonb)
language sql stable security definer set search_path = public, pg_temp as $$
  select t.id, t.name, t.description, t.price, t.capacity, t.payment_qr_path, t.accent_color,
         t.sort_order, greatest(t.capacity - public._seats_taken(t.id), 0),
         t.persons_per_unit, t.person_labels, t.unit_label, t.payment_qrs, t.group_prices
  from public.ticket_types t
  where t.active
  order by t.sort_order, t.id;
$$;
revoke all on function public.public_ticket_types() from public, anon, authenticated;
grant execute on function public.public_ticket_types() to anon, authenticated;

-- label of person k (1-based) in pass u, e.g. "Couple 2 · Female" or "Female"
create or replace function public._slot_label(t public.ticket_types, u int, k int) returns text
language sql immutable set search_path = public, pg_temp as $$
  select case when t.persons_per_unit > 1
              then coalesce(nullif(t.unit_label, ''), 'Group') || ' ' || u || ' · ' || coalesce(t.person_labels[k], 'Person ' || k)
              else coalesce(t.person_labels[1], '') end;
$$;
revoke all on function public._slot_label(public.ticket_types,int,int) from public, anon, authenticated;

-- total for q passes: the group price for q if set, else price x q
create or replace function public._type_total(t public.ticket_types, q int) returns int
language sql immutable set search_path = public, pg_temp as $$
  select coalesce(nullif(t.group_prices ->> q::text, '')::int, t.price * q);
$$;
revoke all on function public._type_total(public.ticket_types,int) from public, anon, authenticated;

-- who each person is: 'student' (girls of the school; signed consent form at school), 'guest' (parent / guest),
-- or 'child' (staff booking only: a staff member's own child, at the staff child price)
create or replace function public._roles_ok(p_roles text[], n int) returns boolean
language sql immutable set search_path = public, pg_temp as $$
  select p_roles is null or coalesce(array_length(p_roles, 1), 0) = 0
      or (array_length(p_roles, 1) = n and not exists (select 1 from unnest(p_roles) r where r is null or r not in ('student', 'guest', 'child')));
$$;
revoke all on function public._roles_ok(text[],int) from public, anon, authenticated;

-- ---------- staff booking helpers ----------
-- People already booked by one staff member (pending + approved staff orders, same email or same mobile).
create or replace function public._staff_used(p_email text, p_phone text) returns int
language sql stable security definer set search_path = public, pg_temp as $$
  select count(*)::int from public.tickets tk join public.orders o on o.id = tk.order_id
   where o.is_staff and o.status in ('pending', 'approved')
     and (lower(o.email) = lower(btrim(coalesce(p_email, '')))
          or (length(regexp_replace(coalesce(p_phone, ''), '\D', '', 'g')) >= 10
              and right(regexp_replace(o.phone, '\D', '', 'g'), 10) = right(regexp_replace(p_phone, '\D', '', 'g'), 10)));
$$;
revoke all on function public._staff_used(text, text) from public, anon, authenticated;

-- Children already booked by one staff member (same matching as _staff_used).
create or replace function public._staff_children_used(p_email text, p_phone text) returns int
language sql stable security definer set search_path = public, pg_temp as $$
  select count(*)::int from public.tickets tk join public.orders o on o.id = tk.order_id
   where o.is_staff and o.status in ('pending', 'approved') and tk.slot = 'Child'
     and (lower(o.email) = lower(btrim(coalesce(p_email, '')))
          or (length(regexp_replace(coalesce(p_phone, ''), '\D', '', 'g')) >= 10
              and right(regexp_replace(o.phone, '\D', '', 'g'), 10) = right(regexp_replace(p_phone, '\D', '', 'g'), 10)));
$$;
revoke all on function public._staff_children_used(text, text) from public, anon, authenticated;

-- Staff page: is this link valid? Returns {discount, max_people} or null. Never returns the key.
create or replace function public.staff_check(p_key text) returns jsonb
language sql stable security definer set search_path = public, pg_temp as $$
  select jsonb_build_object('discount', staff_discount, 'max_people', staff_max_people, 'child_price', staff_child_price,
                            'max_children', staff_max_children)
    from public.event_settings
   where id = 1 and staff_enabled and staff_key <> '' and staff_key = p_key;
$$;
revoke all on function public.staff_check(text) from public, anon, authenticated;
grant execute on function public.staff_check(text) to anon, authenticated;

-- Staff page, before payment: how many more people this staff member (same mobile or email) can book. Null = bad link.
create or replace function public.staff_remaining(p_key text, p_email text, p_phone text) returns int
language sql stable security definer set search_path = public, pg_temp as $$
  select greatest(staff_max_people - public._staff_used(p_email, p_phone), 0)
    from public.event_settings
   where id = 1 and staff_enabled and staff_key <> '' and staff_key = p_key;
$$;
revoke all on function public.staff_remaining(text, text, text) from public, anon, authenticated;
grant execute on function public.staff_remaining(text, text, text) to anon, authenticated;

-- Same check, with children: {"people": n, "children": n} still bookable. Null = bad link.
create or replace function public.staff_quota(p_key text, p_email text, p_phone text) returns jsonb
language sql stable security definer set search_path = public, pg_temp as $$
  select jsonb_build_object('people',   greatest(staff_max_people - public._staff_used(p_email, p_phone), 0),
                            'children', greatest(staff_max_children - public._staff_children_used(p_email, p_phone), 0))
    from public.event_settings
   where id = 1 and staff_enabled and staff_key <> '' and staff_key = p_key;
$$;
revoke all on function public.staff_quota(text, text, text) from public, anon, authenticated;
grant execute on function public.staff_quota(text, text, text) to anon, authenticated;

-- Admin: the secret staff link key (made on first use). p_new = true makes a new one; the old link stops working.
create or replace function public.admin_staff_key(p_new boolean default false) returns text
language plpgsql volatile security definer set search_path = public, pg_temp as $$
declare k text;
begin
  if not public.is_admin() then raise exception 'FORBIDDEN'; end if;
  update public.event_settings set staff_key = public._rand_token()
   where id = 1 and (p_new or staff_key = '');
  select staff_key into k from public.event_settings where id = 1;
  return k;
end $$;
revoke all on function public.admin_staff_key(boolean) from public, anon, authenticated;
grant execute on function public.admin_staff_key(boolean) to authenticated;

-- ---------- public: create_order ----------
-- Price comes from ticket_types, never the client. Errors are plain codes the page maps to messages.
-- One QR code per order (admits everyone on it); qty = passes; people = qty x persons_per_unit,
-- each with a name (Aadhaar images optional, no longer asked for).
-- p_staff_key (from the secret staff link): staff discount, and at most staff_max_people people per staff member,
-- counted over their pending + approved staff orders by the same mobile number or email.
drop function if exists public.create_order(bigint,int,text,text,text,text,text,text[]);          -- pre-v2 signature (no Aadhaar)
drop function if exists public.create_order(bigint,int,text,text,text,text,text,text[],text[]);        -- pre-staff signature
drop function if exists public.create_order(bigint,int,text,text,text,text,text,text[],text[],text);   -- pre-roles signature
create or replace function public.create_order(
  p_type_id bigint, p_qty int, p_buyer_name text, p_email text, p_phone text,
  p_payer_name text, p_screenshot_path text, p_names text[], p_id_paths text[], p_staff_key text default null,
  p_roles text[] default null
) returns text
language plpgsql security definer set search_path = public, extensions, pg_temp as $$
declare
  s   public.event_settings%rowtype;
  t   public.ticket_types%rowtype;
  v_email text := lower(btrim(coalesce(p_email, '')));
  v_name  text := btrim(coalesce(p_buyer_name, ''));
  v_payer text := btrim(coalesce(p_payer_name, ''));
  v_phone text := btrim(coalesce(p_phone, ''));
  v_order public.orders%rowtype;
  v_left  int; v_people int; i int; nm text;
  v_staff boolean := p_staff_key is not null; v_price int; v_used int; v_total int;
begin
  select * into s from public.event_settings where id = 1;
  if not found or not s.sales_open
     or (s.sales_start is not null and now() < s.sales_start)
     or (s.sales_end   is not null and now() > s.sales_end) then
    raise exception 'SALES_CLOSED';
  end if;

  if p_qty is null or p_qty < 1 then raise exception 'BAD_QTY'; end if;
  if p_qty > s.max_per_order then raise exception 'MAX_PER_ORDER:%', s.max_per_order; end if;
  if length(v_name) < 2 or length(v_name) > 80 then raise exception 'BAD_NAME'; end if;
  if length(regexp_replace(v_phone, '\D', '', 'g')) < 10 or length(v_phone) > 20 then raise exception 'BAD_PHONE'; end if;
  if v_email !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' or length(v_email) > 120 then raise exception 'BAD_EMAIL'; end if;
  if length(v_payer) < 2 or length(v_payer) > 80 then raise exception 'BAD_PAYER'; end if;

  -- Lock the ticket type row: concurrent buyers of this type queue here, so seats cannot be oversold.
  select * into t from public.ticket_types where id = p_type_id and active for update;
  if not found then raise exception 'TYPE_UNAVAILABLE'; end if;
  v_people := p_qty * t.persons_per_unit;

  if p_names is null or coalesce(array_length(p_names, 1), 0) <> v_people then raise exception 'BAD_ATTENDEES'; end if;
  foreach nm in array p_names loop
    if length(btrim(coalesce(nm, ''))) < 2 or length(nm) > 80 then raise exception 'BAD_ATTENDEES'; end if;
  end loop;
  if not public._roles_ok(p_roles, v_people) then raise exception 'BAD_ATTENDEES'; end if;
  -- child passes: staff booking only, one person per pass
  if 'child' = any(coalesce(p_roles, '{}')) and (not v_staff or t.persons_per_unit <> 1) then raise exception 'BAD_ATTENDEES'; end if;

  v_price := t.price; v_total := public._type_total(t, p_qty);   -- group price for this many passes
  if v_staff then
    if not s.staff_enabled or s.staff_key = '' or p_staff_key is distinct from s.staff_key then raise exception 'BAD_STAFF_LINK'; end if;
    v_price := round(t.price * (100 - s.staff_discount) / 100.0);   -- staff: discount per adult, fixed price per child
    v_total := (select coalesce(sum(case when r = 'child' then s.staff_child_price else v_price end), 0)::int
                  from unnest(case when coalesce(array_length(p_roles, 1), 0) = 0 then array_fill('guest'::text, array[v_people]) else p_roles end) r);
    -- one staff member = same mobile (last 10 digits) or same email. Lock both so two tabs cannot pass the check together.
    perform pg_advisory_xact_lock(hashtext('staff-phone:' || right(regexp_replace(v_phone, '\D', '', 'g'), 10)));
    perform pg_advisory_xact_lock(hashtext('staff-email:' || v_email));
    v_used := public._staff_used(v_email, v_phone);
    if v_used + v_people > s.staff_max_people then
      raise exception 'STAFF_LIMIT:%', greatest(s.staff_max_people - v_used, 0);
    end if;
    v_used := public._staff_children_used(v_email, v_phone);   -- children: at most staff_max_children per staff member
    if v_used + (select count(*) from unnest(coalesce(p_roles, '{}')) r where r = 'child') > s.staff_max_children then
      raise exception 'STAFF_CHILD_LIMIT:%', greatest(s.staff_max_children - v_used, 0);
    end if;
  end if;

  -- Aadhaar images are no longer collected (the page sends an empty list). If a list is sent, it must still be
  -- one image per person: uploaded through the public uploader, all different, never used before.
  if coalesce(array_length(p_id_paths, 1), 0) = 0 then
    p_id_paths := array_fill(null::text, array[v_people]);
  elsif array_length(p_id_paths, 1) <> v_people
     or (select count(distinct x) from unnest(p_id_paths) x) <> v_people then
    raise exception 'BAD_IDS';
  else for i in 1..v_people loop
    if p_id_paths[i] is null or p_id_paths[i] !~ '^[0-9a-f-]{36}\.jpg$'
       or not exists (select 1 from storage.objects o where o.bucket_id = 'ids' and o.name = p_id_paths[i])
       or exists (select 1 from public.tickets where id_path = p_id_paths[i]) then
      raise exception 'BAD_IDS:%', i;
    end if;
  end loop; end if;

  -- screenshot must be a path uploaded through the public uploader and not used anywhere else
  if p_screenshot_path is null or p_screenshot_path !~ '^[0-9a-f-]{36}\.jpg$'
     or not exists (select 1 from storage.objects o where o.bucket_id = 'screenshots' and o.name = p_screenshot_path)
     or exists (select 1 from public.orders where screenshot_path = p_screenshot_path)
     or exists (select 1 from public.dandiya_rentals where screenshot_path = p_screenshot_path) then
    raise exception 'BAD_SCREENSHOT';
  end if;

  v_left := t.capacity - public._seats_taken(t.id);
  if v_left <= 0 then raise exception 'SOLD_OUT'; end if;
  if p_qty > v_left then raise exception 'NOT_ENOUGH_SEATS:%', v_left; end if;

  if (select count(*) from public.orders where lower(email) = v_email and status = 'pending') >= 3 then
    raise exception 'TOO_MANY_PENDING';
  end if;

  insert into public.orders (order_no, token, ticket_code, type_id, type_name, unit_price, qty, amount,
                             buyer_name, email, phone, payer_name, screenshot_path, status, source, is_staff)
  values ('ORD-' || nextval('public.order_no_seq'), public._rand_token(), public._new_ticket_code(), t.id, t.name, round(v_total::numeric / p_qty), p_qty,
          v_total, v_name, v_email, v_phone, v_payer, p_screenshot_path, 'pending', 'online', v_staff)
  returning * into v_order;

  for i in 1..v_people loop
    insert into public.tickets (order_id, attendee_name, id_path, slot)
    values (v_order.id, btrim(p_names[i]), p_id_paths[i],
            case when p_roles[i] = 'student' then 'Student' when p_roles[i] = 'child' then 'Child'
                 else nullif(public._slot_label(t, (i - 1) / t.persons_per_unit + 1, (i - 1) % t.persons_per_unit + 1), '') end);
  end loop;

  return v_order.token;
end $$;
revoke all on function public.create_order(bigint,int,text,text,text,text,text,text[],text[],text,text[]) from public, anon, authenticated;
grant execute on function public.create_order(bigint,int,text,text,text,text,text,text[],text[],text,text[]) to anon, authenticated;

-- ---------- public: get_order (by unguessable token) ----------
-- Names (+ slot labels), the QR code only once approved, and the latest dandiya rental. Never IDs or screenshots.
create or replace function public.get_order(p_token text) returns jsonb
language plpgsql stable security definer set search_path = public, pg_temp as $$
declare o public.orders%rowtype; d public.dandiya_rentals%rowtype;
begin
  if p_token is null or length(p_token) <> 24 then return null; end if;
  select * into o from public.orders where token = p_token;
  if not found then return null; end if;
  select * into d from public.dandiya_rentals where order_id = o.id order by id desc limit 1;
  return jsonb_build_object(
    'order_no', o.order_no, 'status', o.status, 'reject_reason', o.reject_reason,
    'type_id', o.type_id, 'type_name', o.type_name, 'qty', o.qty, 'amount', o.amount,
    'buyer_name', o.buyer_name, 'email', o.email, 'created_at', o.created_at,
    'accent_color', (select accent_color from public.ticket_types where id = o.type_id),
    'people', (select coalesce(jsonb_agg(attendee_name order by id), '[]'::jsonb) from public.tickets where order_id = o.id),
    'consent_ok', o.consent_ok,
    'slots',  (select coalesce(jsonb_agg(coalesce(slot, '') order by id), '[]'::jsonb) from public.tickets where order_id = o.id),
    'code', case when o.status = 'approved' then o.ticket_code end,
    'checked_in', o.checked_in,
    'dandiya', case when d.id is null then null else jsonb_build_object(
        'pairs', d.pairs, 'amount', d.amount, 'status', d.status, 'reject_reason', d.reject_reason,
        'deposit_refunded', d.deposit_refunded, 'created_at', d.created_at) end);
end $$;
revoke all on function public.get_order(text) from public, anon, authenticated;
grant execute on function public.get_order(text) to anon, authenticated;

-- ---------- public: request a dandiya rental for an approved order ----------
create or replace function public.request_dandiya(p_token text, p_pairs int, p_payer_name text, p_screenshot_path text)
returns jsonb language plpgsql security definer set search_path = public, pg_temp as $$
declare s public.event_settings%rowtype; o public.orders%rowtype; v_payer text := btrim(coalesce(p_payer_name, ''));
begin
  select * into s from public.event_settings where id = 1;
  if not s.dandiya_enabled then raise exception 'DANDIYA_OFF'; end if;
  if p_token is null or length(p_token) <> 24 then raise exception 'NOT_FOUND'; end if;
  select * into o from public.orders where token = p_token for update;
  if not found then raise exception 'NOT_FOUND'; end if;
  if o.status <> 'approved' then raise exception 'ORDER_NOT_APPROVED'; end if;
  if exists (select 1 from public.dandiya_rentals where order_id = o.id and status in ('pending','approved')) then
    raise exception 'DANDIYA_EXISTS';
  end if;
  if p_pairs is null or p_pairs < 1 or p_pairs > s.dandiya_max then raise exception 'BAD_PAIRS:%', s.dandiya_max; end if;
  if length(v_payer) < 2 or length(v_payer) > 80 then raise exception 'BAD_PAYER'; end if;
  if p_screenshot_path is null or p_screenshot_path !~ '^[0-9a-f-]{36}\.jpg$'
     or not exists (select 1 from storage.objects x where x.bucket_id = 'screenshots' and x.name = p_screenshot_path)
     or exists (select 1 from public.orders where screenshot_path = p_screenshot_path)
     or exists (select 1 from public.dandiya_rentals where screenshot_path = p_screenshot_path) then
    raise exception 'BAD_SCREENSHOT';
  end if;
  insert into public.dandiya_rentals (order_id, pairs, amount, payer_name, screenshot_path)
  values (o.id, p_pairs, p_pairs * (s.dandiya_rent + s.dandiya_deposit), v_payer, p_screenshot_path);
  return jsonb_build_object('ok', true);
end $$;
revoke all on function public.request_dandiya(text,int,text,text) from public, anon, authenticated;
grant execute on function public.request_dandiya(text,int,text,text) to anon, authenticated;

-- ---------- admin: approve / reject a dandiya rental ----------
create or replace function public.admin_set_dandiya_status(p_id bigint, p_status text, p_reason text default null)
returns jsonb language plpgsql security definer set search_path = public, pg_temp as $$
declare d public.dandiya_rentals%rowtype;
begin
  if not public.is_admin() then raise exception 'FORBIDDEN'; end if;
  if p_status not in ('pending','approved','rejected') then raise exception 'BAD_STATUS'; end if;
  select * into d from public.dandiya_rentals where id = p_id for update;
  if not found then raise exception 'NOT_FOUND'; end if;
  update public.dandiya_rentals set
    status = p_status,
    reject_reason = case when p_status = 'rejected' then nullif(btrim(coalesce(p_reason, '')), '') else null end,
    approved_at   = case when p_status = 'approved' then now() else null end
  where id = d.id returning * into d;
  return to_jsonb(d) - 'screenshot_path';
end $$;
revoke all on function public.admin_set_dandiya_status(bigint,text,text) from public, anon, authenticated;
grant execute on function public.admin_set_dandiya_status(bigint,text,text) to authenticated;

-- ---------- admin: change order status ----------
-- pending -> approved | rejected ; rejected -> pending | approved (seat check) ; approved -> rejected
create or replace function public.admin_set_order_status(p_order_id bigint, p_status text, p_reason text default null)
returns jsonb language plpgsql security definer set search_path = public, pg_temp as $$
declare o public.orders%rowtype; t public.ticket_types%rowtype;
begin
  if not public.is_admin() then raise exception 'FORBIDDEN'; end if;
  if p_status not in ('pending','approved','rejected') then raise exception 'BAD_STATUS'; end if;

  select * into o from public.orders where id = p_order_id for update;
  if not found then raise exception 'NOT_FOUND'; end if;
  if o.status = p_status then return to_jsonb(o) - 'screenshot_path'; end if;

  if not ((o.status = 'pending'  and p_status in ('approved','rejected'))
       or (o.status = 'rejected' and p_status in ('pending','approved'))
       or (o.status = 'approved' and p_status = 'rejected')) then
    raise exception 'BAD_TRANSITION:% -> %', o.status, p_status;
  end if;

  -- a pass with a student is issued only after her signed consent form is received at school
  if p_status = 'approved' and not o.consent_ok
     and exists (select 1 from public.tickets where order_id = o.id and slot = 'Student') then
    raise exception 'CONSENT_MISSING';
  end if;

  if o.status = 'rejected' then      -- seats were released on rejection: take them again, if still free
    select * into t from public.ticket_types where id = o.type_id for update;
    if o.qty > t.capacity - public._seats_taken(t.id) then raise exception 'NO_SEATS_LEFT'; end if;
  end if;

  update public.orders set
    status = p_status,
    reject_reason = case when p_status = 'rejected' then nullif(btrim(coalesce(p_reason, '')), '') else null end,
    approved_at   = case when p_status = 'approved' then now() else null end
  where id = o.id returning * into o;
  return to_jsonb(o) - 'screenshot_path';
end $$;
revoke all on function public.admin_set_order_status(bigint,text,text) from public, anon, authenticated;
grant execute on function public.admin_set_order_status(bigint,text,text) to authenticated;

-- ---------- admin: manual order (cash / complimentary). Issued as approved. ----------
-- Offline / cash sale or complimentary ticket. Email is optional (no email = show or print the ticket instead).
drop function if exists public.admin_create_manual_order(bigint,int,text,text,text,text[],int);          -- pre-roles signature
drop function if exists public.admin_create_manual_order(bigint,int,text,text,text,text[],int,text[]);   -- pre-consent signature
create or replace function public.admin_create_manual_order(
  p_type_id bigint, p_qty int, p_buyer_name text, p_email text, p_phone text,
  p_names text[], p_amount int default null, p_roles text[] default null, p_consent boolean default false
) returns jsonb language plpgsql security definer set search_path = public, extensions, pg_temp as $$
declare t public.ticket_types%rowtype; o public.orders%rowtype; i int; nm text; v_people int;
        v_email text := lower(btrim(coalesce(p_email, '')));
begin
  if not public.is_admin() then raise exception 'FORBIDDEN'; end if;
  if p_qty is null or p_qty < 1 or p_qty > 50 then raise exception 'BAD_QTY'; end if;
  if length(btrim(coalesce(p_buyer_name, ''))) < 2 then raise exception 'BAD_NAME'; end if;
  if v_email <> '' and v_email !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' then raise exception 'BAD_EMAIL'; end if;
  if p_amount is not null and p_amount < 0 then raise exception 'BAD_AMOUNT'; end if;

  select * into t from public.ticket_types where id = p_type_id for update;
  if not found then raise exception 'TYPE_UNAVAILABLE'; end if;
  v_people := p_qty * t.persons_per_unit;
  if p_names is null or coalesce(array_length(p_names, 1), 0) <> v_people then raise exception 'BAD_ATTENDEES'; end if;
  foreach nm in array p_names loop
    if length(btrim(coalesce(nm, ''))) < 2 then raise exception 'BAD_ATTENDEES'; end if;
  end loop;
  if not public._roles_ok(p_roles, v_people) then raise exception 'BAD_ATTENDEES'; end if;
  if 'student' = any(coalesce(p_roles, '{}')) and not coalesce(p_consent, false) then raise exception 'CONSENT_MISSING'; end if;
  if p_qty > t.capacity - public._seats_taken(t.id) then
    raise exception 'NOT_ENOUGH_SEATS:%', greatest(t.capacity - public._seats_taken(t.id), 0);
  end if;

  insert into public.orders (order_no, token, ticket_code, type_id, type_name, unit_price, qty, amount, buyer_name, email,
                             phone, payer_name, status, source, approved_at, consent_ok)
  values ('ORD-' || nextval('public.order_no_seq'), public._rand_token(), public._new_ticket_code(), t.id, t.name, t.price, p_qty,
          coalesce(p_amount, public._type_total(t, p_qty)), btrim(p_buyer_name), v_email, btrim(coalesce(p_phone, '')),
          'manual', 'approved', 'manual', now(), coalesce(p_consent, false))
  returning * into o;
  for i in 1..v_people loop
    insert into public.tickets (order_id, attendee_name, slot)
    values (o.id, btrim(p_names[i]), case when p_roles[i] = 'student' then 'Student' when p_roles[i] = 'child' then 'Child'
                 else nullif(public._slot_label(t, (i - 1) / t.persons_per_unit + 1, (i - 1) % t.persons_per_unit + 1), '') end);
  end loop;
  return jsonb_build_object('order_id', o.id, 'order_no', o.order_no, 'token', o.token);
end $$;
revoke all on function public.admin_create_manual_order(bigint,int,text,text,text,text[],int,text[],boolean) from public, anon, authenticated;
grant execute on function public.admin_create_manual_order(bigint,int,text,text,text,text[],int,text[],boolean) to authenticated;

-- ---------- admin: dandiya sticks sold offline with a pass (cash). Recorded as an approved rental. ----------
create or replace function public.admin_add_dandiya(p_order_id bigint, p_pairs int, p_amount int default null)
returns jsonb language plpgsql security definer set search_path = public, pg_temp as $$
declare s public.event_settings%rowtype; o public.orders%rowtype; d public.dandiya_rentals%rowtype;
begin
  if not public.is_admin() then raise exception 'FORBIDDEN'; end if;
  select * into s from public.event_settings where id = 1;
  select * into o from public.orders where id = p_order_id for update;
  if not found then raise exception 'NOT_FOUND'; end if;
  if o.status <> 'approved' then raise exception 'ORDER_NOT_APPROVED'; end if;
  if p_pairs is null or p_pairs < 1 or p_pairs > greatest(s.dandiya_max, 1) then raise exception 'BAD_PAIRS:%', s.dandiya_max; end if;
  if p_amount is not null and p_amount < 0 then raise exception 'BAD_AMOUNT'; end if;
  if exists (select 1 from public.dandiya_rentals where order_id = o.id and status in ('pending', 'approved')) then
    raise exception 'DANDIYA_EXISTS';
  end if;
  insert into public.dandiya_rentals (order_id, pairs, amount, payer_name, status, approved_at)
  values (o.id, p_pairs, coalesce(p_amount, p_pairs * (s.dandiya_rent + s.dandiya_deposit)), 'Cash (offline)', 'approved', now())
  returning * into d;
  return to_jsonb(d);
end $$;
revoke all on function public.admin_add_dandiya(bigint,int,int) from public, anon, authenticated;
grant execute on function public.admin_add_dandiya(bigint,int,int) to authenticated;

-- ---------- admin: read email templates (column is not directly readable) ----------
create or replace function public.admin_get_email_templates() returns jsonb
language plpgsql stable security definer set search_path = public, pg_temp as $$
begin
  if not public.is_admin() then raise exception 'FORBIDDEN'; end if;
  return (select email_templates from public.event_settings where id = 1);
end $$;
revoke all on function public.admin_get_email_templates() from public, anon, authenticated;
grant execute on function public.admin_get_email_templates() to authenticated;

-- ---------- admin: seats taken per type (for the Ticket types tab) ----------
create or replace function public.admin_type_counts() returns table (type_id bigint, taken int, approved int)
language plpgsql stable security definer set search_path = public, pg_temp as $$
begin
  if not public.is_admin() then raise exception 'FORBIDDEN'; end if;
  return query
    select t.id, public._seats_taken(t.id),
           coalesce((select sum(o.qty)::int from public.orders o where o.type_id = t.id and o.status = 'approved'), 0)
    from public.ticket_types t;
end $$;
revoke all on function public.admin_type_counts() from public, anon, authenticated;
grant execute on function public.admin_type_counts() to authenticated;

-- ---------- scanner: check_in / undo / stats / recent ----------
-- One QR per order: a valid scan admits everyone on the order at once.
-- Returns result + names (array) + count + type_name (+ used_at when already used) + paid dandiya pairs.
create or replace function public.check_in(p_code text) returns jsonb
language plpgsql security definer set search_path = public, pg_temp as $$
declare
  v_code  text := upper(btrim(coalesce(p_code, '')));
  v_who   text := coalesce(auth.jwt() ->> 'email', 'unknown');
  v_id    bigint; o public.orders%rowtype; v_names jsonb; v_pairs int; v_slots jsonb; v_students int;
begin
  if not public.is_staff() then raise exception 'FORBIDDEN'; end if;
  v_id := public._order_for_code(v_code);
  if v_id is null then
    insert into public.scan_log (code, result, scanned_by) values (left(v_code, 40), 'invalid', v_who);
    return jsonb_build_object('result', 'invalid');
  end if;
  select * into o from public.orders where id = v_id;
  select coalesce(jsonb_agg(attendee_name order by id), '[]'::jsonb), coalesce(jsonb_agg(coalesce(slot, '') order by id), '[]'::jsonb),
         count(*) filter (where slot = 'Student')::int
    into v_names, v_slots, v_students from public.tickets where order_id = o.id;
  select coalesce(sum(pairs), 0)::int into v_pairs from public.dandiya_rentals where order_id = o.id and status = 'approved';

  if o.status <> 'approved' then
    insert into public.scan_log (code, result, scanned_by) values (v_code, 'not_valid', v_who);
    return jsonb_build_object('result', 'not_valid', 'names', v_names, 'slots', v_slots, 'students', v_students, 'count', jsonb_array_length(v_names), 'type_name', o.type_name);
  end if;

  update public.orders set checked_in = true, checked_in_at = now(), checked_in_by = v_who
   where id = o.id and checked_in = false
   returning * into o;
  if found then
    update public.tickets set used = true, used_at = o.checked_in_at, used_by = v_who where order_id = o.id;
    insert into public.scan_log (code, result, scanned_by) values (v_code, 'ok', v_who);
    return jsonb_build_object('result', 'ok', 'names', v_names, 'slots', v_slots, 'students', v_students, 'count', jsonb_array_length(v_names),
                              'type_name', o.type_name, 'order_no', o.order_no, 'code', v_code, 'used_at', o.checked_in_at,
                              'dandiya_pairs', v_pairs);
  end if;
  select * into o from public.orders where id = v_id;
  insert into public.scan_log (code, result, scanned_by) values (v_code, 'already_used', v_who);
  return jsonb_build_object('result', 'already_used', 'names', v_names, 'slots', v_slots, 'students', v_students, 'count', jsonb_array_length(v_names),
                            'type_name', o.type_name, 'order_no', o.order_no, 'code', v_code, 'used_at', o.checked_in_at,
                            'dandiya_pairs', v_pairs);
end $$;
revoke all on function public.check_in(text) from public, anon, authenticated;
grant execute on function public.check_in(text) to authenticated;

-- Undo the calling user's most recent successful check-in (the whole group becomes un-checked).
create or replace function public.undo_check_in() returns jsonb
language plpgsql security definer set search_path = public, pg_temp as $$
declare v_who text := coalesce(auth.jwt() ->> 'email', 'unknown'); l public.scan_log%rowtype; v_id bigint; v_names jsonb;
begin
  if not public.is_staff() then raise exception 'FORBIDDEN'; end if;
  select * into l from public.scan_log
   where result = 'ok' and undone = false and scanned_by = v_who
   order by id desc limit 1 for update;
  if not found then return jsonb_build_object('result', 'nothing_to_undo'); end if;
  v_id := public._order_for_code(l.code);
  update public.orders set checked_in = false, checked_in_at = null, checked_in_by = null where id = v_id;
  update public.tickets set used = false, used_at = null, used_by = null where order_id = v_id;
  update public.scan_log set undone = true where id = l.id;
  insert into public.scan_log (code, result, scanned_by) values (l.code, 'undone', v_who);
  select coalesce(jsonb_agg(attendee_name order by id), '[]'::jsonb) into v_names from public.tickets where order_id = v_id;
  return jsonb_build_object('result', 'undone', 'code', l.code, 'names', v_names, 'count', jsonb_array_length(v_names));
end $$;
revoke all on function public.undo_check_in() from public, anon, authenticated;
grant execute on function public.undo_check_in() to authenticated;

create or replace function public.scan_stats() returns jsonb
language plpgsql stable security definer set search_path = public, pg_temp as $$
begin
  if not public.is_staff() then raise exception 'FORBIDDEN'; end if;
  return (select jsonb_build_object(
            'checked_in', count(*) filter (where t.used),
            'total', count(*))
          from public.tickets t join public.orders o on o.id = t.order_id
          where o.status = 'approved');
end $$;
revoke all on function public.scan_stats() from public, anon, authenticated;
grant execute on function public.scan_stats() to authenticated;

drop function if exists public.recent_scans(int);   -- return columns changed in v2
create or replace function public.recent_scans(p_limit int default 20)
returns table (code text, result text, names text, people int, type_name text, created_at timestamptz, undone boolean)
language plpgsql stable security definer set search_path = public, pg_temp as $$
begin
  if not public.is_staff() then raise exception 'FORBIDDEN'; end if;
  return query
    select l.code, l.result,
           (select string_agg(t.attendee_name, ', ' order by t.id) from public.tickets t where t.order_id = x.oid),
           (select count(*)::int from public.tickets t where t.order_id = x.oid),
           o.type_name, l.created_at, l.undone
    from public.scan_log l
    left join lateral (select public._order_for_code(l.code) as oid) x on true
    left join public.orders o on o.id = x.oid
    order by l.id desc limit least(greatest(coalesce(p_limit, 20), 1), 100);
end $$;
revoke all on function public.recent_scans(int) from public, anon, authenticated;
grant execute on function public.recent_scans(int) to authenticated;

-- ================================ v4 setup ================================
-- Aadhaar photos are no longer collected: no public uploads to the "ids" bucket.
drop policy if exists "ids public upload" on storage.objects;

-- One General Pass with group prices (edit in Admin > Ticket types). Female Solo and Couple Pass go off sale.
insert into public.ticket_types (name, description, price, capacity, active, sort_order, persons_per_unit, group_prices)
select 'General Pass', 'For girls of our school, their parents and guests. One QR admits up to 5 people.', 300, 500, true, 0, 1,
       '{"2":550,"3":807,"4":1052,"5":1285}'::jsonb
 where not exists (select 1 from public.ticket_types where name = 'General Pass');
update public.ticket_types set active = false where name in ('Female Solo', 'Couple Pass');

-- Up to 5 people on one QR; event now starts at 4 PM; consent-form line in the instructions panel.
update public.event_settings set max_per_order = 5, date_text = replace(date_text, '6 PM', '4 PM') where id = 1;
update public.event_settings
   set instructions_text = concat_ws(E'\n', nullif(instructions_text, ''),
       '• School students (girls only) must fill in and submit the signed consent form at school before the event.')
 where id = 1 and instructions_text not ilike '%consent%';
